export const FETCH_CONTACTS_INVITATIONS = "FETCH_CONTACTS_INVITATIONS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UPDATE_INVITATIONS = "UPDATE_INVITATIONS";
export const UPDATE_CONTACTS = "UPDATE_CONTACTS";
