export const FETCH_CONTACTS_INVITATIONS = "FETCH_CONTACTS_INVITATIONS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UPDATE_INVITATIONS = "UPDATE_INVITATIONS";
export const UPDATE_CONTACTS = "UPDATE_CONTACTS";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const UPDATE_USER_IMAGE = "UPDATE_USER_IMAGE";
export const SET_USER_DATA = "SET_USER_DATA";
export const RESET_LISTS = "RESET_LISTS";
