export const FETCH_CONTACTS_INVITATIONS = "FETCH_CONTACTS_INVITATIONS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const FETCH_INVITATIONS = "FETCH_INVITATIONS";
export const APPROVE_INVITATION = "APPROVE_INVITATION";
export const REJECT_INVITATION = "REJECT_INVITATION";
