POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "email": "cookiemonster9@gmail.com",
  "password": "authtest"
}

###
#get w/o valid cookie
GET http://localhost:3001/api/user/
###
#get with valid cookie
GET http://localhost:3001/api/user/
Cookie: auth_token=j%3A%7B%22token%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc0MzA4MjV9.2bEwEgWD4xgahs_3bH1WZgOy8jiFfUdB4RLpSnlPHyc%22%7D; Max-Age=3; Path=/; Expires=Fri, 14 Aug 2020 18:47:09 GMT; HttpOnly